accounts:
  - name: alice
    coins: ["20000uhid", "200000000stake"]
  - name: bob
    coins: ["10000uhid", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
host:
  rpc: ":26657"
  p2p: ":26656"
  prof: ":6061"
  grpc: ":9095"
  grpc-web: ":9093"
  api: ":1318"
  frontend: ":8081"
  dev-ui: ":12346"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5000uhid", "100000stake"]
